name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test
      run: |
        npm install
        npm run build
        npm pack
        cd test-app
        npm install
        npm install ../imagekit-next-*.tgz
        npm run test:e2e
      env:
        CI: true

 